# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Giphy_Search_ReactorKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'ReactorKit'
  pod 'SnapKit'
  pod 'SwiftLint'

  # Pods for Giphy_Search_ReactorKit

end
